# Generated by Django 5.0.6 on 2024-06-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock',
            new_name='stockEnquiry',
        ),
    ]
