# Generated by Django 5.0.6 on 2024-06-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_rename_stock_stockenquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stockEnquiry',
            new_name='stockList',
        ),
    ]
