# Generated by Django 5.0.6 on 2024-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_rename_stockenquiry_stocklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='stockList',
        ),
    ]
