# Generated by Django 5.0.6 on 2024-06-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_stock_delete_stocklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='stockList',
        ),
    ]
