# Generated by Django 5.0.6 on 2024-09-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_attendance_present_alter_attendance_time_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_days_present', models.IntegerField()),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonuses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.member')),
            ],
        ),
    ]
