# Generated by Django 5.0.6 on 2024-09-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
